name: bcp47
version: 0.1.0.0
github:  "freckle/bcp47"
license: MIT
author: "Evan Rutledge Borden"
maintainer: "engineering@freckle.com"
copyright: "2019 Freckle Education"

extra-source-files:
- README.md
- ChangeLog.md
category: Data, Data Structures
synopsis: Language tags as specified by BCP 47
description: |
  /Language tags for use in cases where it is desirable to indicate the/
  /language used in an information object./
  .
  / - /<https://tools.ietf.org/html/bcp47>
  .
  This package exposes a language tag data type 'BCP47' and a 'Trie' data
  structure for collecting and querying information that varies based on
  language tag.
  .
  @
    import Data.BCP47 (en, enGB, es)
    import Data.BCP47.Trie (Trie, fromList, lookup)

    color :: Trie Text
    color = fromList [(en, "color"), (es, "colour")]

    main = do
      print $ match en color -- Just "color"
      print $ match enGB color -- Nothing
      print $ lookup enGB color -- Just "color"
  @

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: library
  dependencies:
  - QuickCheck
  - containers
  - generic-arbitrary
  - iso3166-country-codes
  - iso639
  - megaparsec
  - text

tests:
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - doctest
  spec:
    main: Main.hs
    source-dirs: tests
    dependencies:
    - QuickCheck
    - bcp47
    - containers
    - hspec
    - iso3166-country-codes
    - iso639
    - text
