name: bcp47
version: 0.1.0.0
github:  "frontrow/bcp-47"
license: MIT
author: "Evan Rutledge Borden"
maintainer: "engineering@freckle.com"
copyright: "2018 Freckle Education"

extra-source-files:
- README.md
- ChangeLog.md
description:
  https://tools.ietf.org/html/bcp47
  .
  Language tags for use in cases where it is desirable to indicate the language
  used in an information object.

dependencies:
- QuickCheck
- base >= 4.7 && < 5
- iso3166-country-codes
- iso639
- megaparsec
- text
- containers

library:
  source-dirs: src

tests:
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - doctest
  spec:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - bcp47
      - hspec
