name: bcp47-orphans
version: 0.1.0.3
github: "freckle/bcp47"
license: MIT
author: "Evan Rutledge Borden"
maintainer: "engineering@freckle.com"
copyright: "2019 Freckle Education"
category: Orphan Instances

extra-source-files:
- README.md
- ChangeLog.md
description: Orphan instances for the BCP47 type
synopsis: BCP47 orphan instances

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: library
  dependencies:
  - bcp47
  - cassava
  - errors
  - esqueleto < 3.5
  - hashable
  - http-api-data
  - path-pieces
  - persistent < 2.14
  - text

tests:
  spec:
    main: Main.hs
    source-dirs: tests
    dependencies:
    - QuickCheck < 2.15
    - bcp47
    - bcp47-orphans
    - cassava
    - hspec
    - path-pieces
    - persistent < 2.14
