name: bcp47-orphans
version: 0.1.0.0
github: "frontrow/bcp-47"
license: MIT
author: "Evan Rutledge Borden"
maintainer: "engineering@freckle.com"
copyright: "2019 Freckle Education"

extra-source-files:
- README.md
- ChangeLog.md
description: Orphan instances for the BCP47 type

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: library
  dependencies:
  - aeson
  - bcp47
  - cassava
  - errors
  - esqueleto
  - hashable
  - path-pieces
  - persistent
  - text

tests:
  spec:
    main: Main.hs
    source-dirs: tests
    dependencies:
    - QuickCheck
    - aeson
    - bcp47
    - bcp47-orphans
    - cassava
    - hspec
    - path-pieces
    - persistent
