name: bcp47-cassava
version: 0.1.0.0
github: "frontrow/bcp-47"
license: MIT
author: "Evan Rutledge Borden"
maintainer: "engineering@freckle.com"
copyright: "2019 Freckle Education"

extra-source-files:
- README.md
- ChangeLog.md
description: ToField and FromField instances for using the BCP47 type with Cassava

dependencies:
- QuickCheck
- base >= 4.7 && < 5
- bcp47
- cassava
- text

library:
  source-dirs: library

tests:
  spec:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - bcp47-cassava
      - hspec
